change docker image name

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,7 +44,7 @@ jobs:
             exit 1
           fi
           
-          EXISTING_VERSION=$(docker pull "ghcr.io/${{ github.repository }}:$LATEST_VERSION" || echo "not found")
+          EXISTING_VERSION=$(docker pull "ghcr.io/${{ github.repository_owner }}/graalvm-oracle-jre:$LATEST_VERSION" || echo "not found")
           if [ "$EXISTING_VERSION" != "not found" ]; then
             echo "Docker image with Tag `$LATEST_VERSION` already exists."
             echo "new_version=false" >> $GITHUB_ENV
