remove complicated logic with platforms because oracle base image supports only 2 platforms

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,13 +15,6 @@ jobs:
     strategy:
       matrix:
         java_version: [17, 21, 22]
-        include:
-          - java_version: 17
-            platforms: linux/amd64,linux/arm64/v8
-          - java_version: 21
-            platforms: linux/amd64,linux/arm64/v8
-          - java_version: 22
-            platforms: linux/amd64,linux/arm64/v8
 
     steps:
       - name: Set up Docker Buildx
@@ -32,7 +25,7 @@ jobs:
       - name: Install dependencies
         run: |
           sudo apt-get update
-          sudo apt-get install -y curl grep sed jq
+          sudo apt-get install -y curl grep sed
 
       - name: Log in to GitHub Container Registry
         run: |
@@ -49,22 +42,15 @@ jobs:
             echo "Version not found" 
             exit 1
           fi
-
+          
           echo "Latest GraalVM version for Java $JAVA_VERSION: $LATEST_VERSION"
-
-          PLATFORM_MISSING=false
-          for PLATFORM in ${{ matrix.platforms }}; do
-            if ! docker manifest inspect "ghcr.io/${{ github.repository_owner }}/graalvm-oracle-jre:$LATEST_VERSION" | jq -e '.manifests[] | select(.platform.architecture == "'"${PLATFORM#*/}"'")' >/dev/null; then
-              PLATFORM_MISSING=true
-              echo "Platform $PLATFORM does not exist for $LATEST_VERSION."
-            fi
-          done
-
-          if [ "$PLATFORM_MISSING" = "false" ]; then
-            echo "Docker image with Tag $LATEST_VERSION for all platforms already exists."
+          
+          EXISTING_VERSION=$(docker pull "ghcr.io/${{ github.repository_owner }}/graalvm-oracle-jre:$LATEST_VERSION" || echo "not found")
+          if [ "$EXISTING_VERSION" != "not found" ]; then
+            echo "Docker image with Tag `$LATEST_VERSION` already exists."
             echo "new_version=false" >> $GITHUB_ENV
           else
-            echo "New version detected or missing platforms for Java $JAVA_VERSION: $LATEST_VERSION"
+            echo "New version detected for Java $LATEST_VERSION"
             echo "new_version=true" >> $GITHUB_ENV
             echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
             echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV
@@ -81,7 +67,7 @@ jobs:
           build-args: |
             GRAALVM_VERSION=${{ env.LATEST_VERSION }}
             JAVA_MAJOR_VERSION=${{ matrix.java_version }}
-          platforms: ${{ matrix.platforms }}
+          platforms: linux/amd64,linux/arm64/v8
           tags: |
             ghcr.io/${{ github.repository_owner }}/graalvm-oracle-jre:${{ env.LATEST_VERSION }}
           push: true
