fixed EXISTING_VERSION checking

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,12 +41,12 @@ jobs:
             exit 1
           fi
           
-          EXISTING_VERSION=$(docker pull "ghcr.io/${{ github.repository }}:$JAVA_VERSION-$LATEST_VERSION" || echo "not found")
+          EXISTING_VERSION=$(docker pull "ghcr.io/${{ github.repository }}:$LATEST_VERSION" || echo "not found")
           if [ "$EXISTING_VERSION" != "not found" ]; then
-            echo "Version $LATEST_VERSION for Java $JAVA_VERSION already exists."
+            echo "Docker image with Tag `$LATEST_VERSION` already exists."
             echo "new_version=false" >> $GITHUB_ENV
           else
-            echo "New version detected for Java $JAVA_VERSION: $LATEST_VERSION"
+            echo "New version detected for Java $LATEST_VERSION"
             echo "new_version=true" >> $GITHUB_ENV
             echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
             echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV
